### ISSUE TITLE
Order of likes

### ISSUE THREAD

**Issue by v-braun** [sindresorhus/likes#2]
Love this repo, but can you order the new entries first?

**Comment by LasaleFamine** [comment]
I think we need to ask the feature to [Idnan](https://github.com/Idnan/like-on-git).

**Comment by websemantics** [comment]
Excellent idea, .. I had a similar need and thought someone should develop a product for that,
 for anyone interested, here's few thoughts about the subject I wrote a while ago, https://github.com/websemantics/journey

**Comment by alexyorke** [comment]
@sindresorhus What are your thoughts on this?

**Comment by Idnan** [comment]
@LasaleFamine @v-braun @Decagon sorry guys, i am really super busy with some of the projects at office. I will work on it as soon as I get some time.
